// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIXPlantUMLEditor
{
    internal sealed partial class Vsix
    {
        public const string Id = "VSIXPlantUMLEditor.ea30be9e-09b6-4b4d-9618-88f92b84c529";
        public const string Name = "VSIXPlantUMLEditor";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Karlo Kranjčina";
        public const string Tags = "";
    }
}
